export const API_ERROR = "EVENT/API_ERROR_RECEIVED";
export const WEATHER_DATA_RECEIVED = "EVENT/WEATHER_DATA_RECEIVED";
export const METRICS_LIST_RECEIVED = "EVENT/METRICS_LIST_RECEIVED";
export const TOGGLE_METRIC = "EVENT/TOGGLE_METRIC";
export const NEW_MEASUREMENT_RECEIVED = "EVENT/NEW_MEASUREMENT_RECEIVED";

export const OIL_RECEIVED = "EVENT/OIL_RECEIVED";
export const FLARE_RECEIVED = "EVENT/FLARE_RECEIVED";
export const WATER_RECEIVED = "EVENT/WATER_RECEIVED";
export const TUBING_RECEIVED = "EVENT/TUBING_RECEIVED";
export const CASING_RECEIVED = "EVENT/CASING_RECEIVED";
export const VALVE_RECEIVED = "EVENT/VALVE_RECEIVED";

export const NEW_OIL_RECEIVED = "EVENT/NEW_OIL_RECEIVED";
export const NEW_FLARE_RECEIVED = "EVENT/NEW_FLARE_RECEIVED";
export const NEW_WATER_RECEIVED = "EVENT/NEW_WATER_RECEIVED";
export const NEW_TUBING_RECEIVED = "EVENT/NEW_TUBING_RECEIVED";
export const NEW_CASING_RECEIVED = "EVENT/NEW_CASING_RECEIVED";
export const NEW_VALVE_RECEIVED = "EVENT/NEW_VALVE_RECEIVED";
